### ISSUE TITLE
Implement REST endpoints for managing migration scripts

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1072]

**Comment by metas-ts** [comment]
Hi @teosarca , this issue sounds interesting, please add some documentation

**Comment by metas-ts** [comment]
note @IT: please check if it works in a docker-instance

**Comment by metas-rc** [comment]
Results of IT

Tested on a docker instance ( https://dev137.metasfresh.com)

* Login as sys admin
* OK : The migration script rest endpoints are present in the docker instancec's swagger
* Execute enable migration script endpoint 
/rest/api/dev/migrationScriptsLogger/enableIt
enableLogMigrationScripts
*  Do something that triggers a migration script creatino (create an ad_element) 
* Execute endpoint 
/rest/api/dev/migrationScriptsLogger/scripts/current
getCurrentScript
* => OK The field contains the insert queries 
* Run endpoint T
/rest/api/dev/migrationScriptsLogger/disableIt
disableLogMigrationScripts
* Make a change that trggers migration script ( change something in the element or create a new one) 
* Execute endpoint 
/rest/api/dev/migrationScriptsLogger/scripts/current
getCurrentScript again
* => OK: No new lines were added to the script

* Execute endpoint /rest/api/dev/migrationScriptsLogger
getInfo
 * => OK info about the script are displayed (e.g. the name of the script)

* Execute endpoint 
/rest/api/dev/migrationScriptsLogger/scripts/{filename}
getScript
* Set a filename ( e.g. the current file) without the folders ( e.g.  	
5506420_migration_2018-11-13_postgresql.sql)
 * => NOK: Error respone: 
![image](https://user-images.githubusercontent.com/16001442/48493446-80b3a380-e834-11e8-82a6-fe34eaa37a22.png)

* The problem is that the " .sql"  part is somehow cut and the filename is no longer valid.

Followup created https://github.com/metasfresh/metasfresh-webui-api/issues/1108

* Execute endpoint 
/rest/api/dev/migrationScriptsLogger/scripts/current
deleteCurrentScript

* now execute /rest/api/dev/migrationScriptsLogger/scripts/current
getCurrentScript again
 * => OK :You get an error respone because the file does not exist any more
