### ISSUE TITLE
Fix webui window update from remote editing

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#1125]
### Is this a bug or feature request?
Bug, follow-up to https://github.com/metasfresh/metasfresh/issues/4450

### What is the current behavior?

from some less common windows, if you edit a record, then the edit does not appear in another user's window without a refresh

#### Which are the steps to reproduce?

you can try it with the inventory-count window, e.g. on [w101](https://w101.metasfresh.com:8443/window/540458)

### What is the expected or desired behavior?

changes in one browser window shall be propagated

**Comment by metas-dh** [comment]
Results of IT1
tested in release

* physical inventory window updated correctly when the process for counting lines was run in inventory-count window, no more refresh in physical inventory necessary in order to complete the document: OK
* after deleting the lines in physical inventory window, i still had to refresh the inventory-count window in order to see that there were no inventory lines anymore: NOK imho: 
=> checked w/ metas-mk: not nice, but OK for now
