### ISSUE TITLE
Products proposal: display the prices paid by other customers

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1148]

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. selecting a product in Products Proposal: Action `Other customers` becomes available: OK (only in sales order, not bpartner window: OK afiau)
2. selecting the `Other customers` action: 
    * opens 2nd modal, `Other customers`: OK 
    * prices for other customers for the selected product are displayed: OK
    * also different price for the same customer (= manual price from a different sales order) for the selected product is displayed: OK afaiu
    * also shows the same price for the same customer (from same pricelist i suppose): why?
    * Last sales invoice date shows the sales invoice where that price was used: OK
3. `Add products` action in the 2nd modal window: sets the price for the product selected, in the 1st modal window, 2nd modal closes: OK, but why is it called `Add products`? i found that confusing, since it's for taking a different price, not adding a product...?
4. `Add products` action in the 2nd modal window: works sev. times, so you can change the price more than once: OK
5. after price from other customer is taken, action `Save to pricelist` becomes available: OK
6.  `Save to pricelist`: selected price is set in the pricelist used for the resp. product used in the sales order: OK
7.  After the different price is saved to pricelist, this same price is also still displayed as price from other customers, although it's the one already set: OK? shouldn't it update accordingly?
8. `Back` action in the 2nd modal window: it's in the quick action dropdown, works fine to close the 2nd modal and get back to the 1st, but there is also a general `Back` button at the top, which closes the whole modal overview, might be confusing for the user (i clicked that general button expecting getting back to the 1st modal window, maybe we should rename it to `Cancel`?) => solved in #1086!
9. `More products` action to show more available products from fallback PLV: also still available and working fine: OK

questions / problems:
* 2nd modal, `Other customers`: also shows the same price for the same customer (from same pricelist i suppose): why?
(=> found the names a bit confusing: `Other customers`, `Add products`, `Back` )



checked remaining question with metas-mk: OK as it is
