### ISSUE TITLE
Provide initialValue flag in document field's validStatus

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#203]
the initialValue shall be set to:
* true if the value it's an initial value (newly created document or document was just loaded from database)
* false if the value was changed (compared with what we got from database or the one we initialized in case of new documents)
* null if the status is not known (basically this will happen on document level)

![image](https://cloud.githubusercontent.com/assets/1244701/23554856/723bd35c-002f-11e7-8e17-7b04e5be01b2.png)

**Comment by metas-lc** [comment]
IT: 
initial value on new document: true
initial value on opening existing document: true
initial value on changing a field: true ...OK?
what means status not known? not sure how to get the null value

**Comment by metas-lc** [comment]
@teosarca thanks for the info. 
Results:
- initial value on new document: true -> OK
- initial value on opening existing document: true -> OK
- initial value on changing a field+save: true -> OK
- initial value on removing a mandatory field: false -> OK
(used mandatory field so that my document won't save, so i can have different value from database)
