### ISSUE TITLE
Honor window's create new and delete logics

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#221]
### What is the current behavior?
The create new and delete settings from application dictionary are not respected at all.
They were implemented only for included documents.

#### Which are the steps to reproduce?
* open receipt candidates or shipment candidates for example
* press create new => you are allowed

### What is the expected or desired behavior?
Shall work like on swing.

**Comment by metas-dh** [comment]
Results of IT 1
tested on w101

create new logic:
* material receipt candidate & receipt schedule candidate: not possible, error in WebUI when pressing New, no New button available in Swing: OK
* OLCand and purchase candidate: New is possible, but the mandatory fields cannot be filled bc of read-only: same in WebUI and Swing: OK
* invoice candidates: New is possible, but the mandatory fields cannot be filled bc of read-only: same in WebUI and Swing: OK

delete logic:
* order / inout cannot be deleted (with Delete button) when completed / processed: same in WebUI and Swing: OK
* bpartner cannot be deleted because references from other documents: same in WebUI and Swing: OK
