### ISSUE TITLE
jenkins shall not trigger metasfresh build when metasfresh-webui is built

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#229]

**Comment by metas-ts** [comment]
hi, as written in the private chat, the metasfresh build works as a dispatcher.

We can extract that feature into a dedicated jenkins job, but first i would like to understand what outcome you expect. So in order to proceed with this task, please let me know what it is exactly you want to achieve and why you want not to trigger metasfresh build.

**Comment by teosarca** [comment]
my expected outcome is:
when metasfresh-webui build is triggered then it shall trigger metasfresh-dist, metasfresh-dist-orgs ... after.
But it shall not trigger metasfresh build again because takes a lot of time, resources etc etc.

do i miss something?

**Comment by metas-ts** [comment]
> do i miss something?

yes, i think you do :-). If you check the `metasfresh` build that is actually triggered by `metasfresh-webui`, you see that it does not take a lot of time. It only takes as much time as the dedicated "dispatcher" job i meantioned would also take.

**Comment by teosarca** [comment]
and what's that dispatcher doing?
I guess we have it there because now jenkins (in pipeline mode?) is no longer discovering the dependencies as it did long time ago, right?

**Comment by metas-ts** [comment]
> and what's that dispatcher doing?

right, it's calling the *-dist jbos, *and* also notifying zapier which then can trigger other stuff

> I guess we have it there because now jenkins (in pipeline mode?) is no longer discovering the dependencies as it did long time ago, right?

yes. but that's not because of pipeline mode..we removed that long time ago, because the maven plugin slowed down everything *a lot* (i think mostly because it insisted in archiving each artifact, which meant that a lot of data had to be transferred between agents and master)

**Comment by teosarca** [comment]
closing it. preserving status quo
