### ISSUE TITLE
Cannot create a new BPartner contact

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#256]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* create new partner
* add new contact => nothing happens
* try again to add new contact and you get:
```
Error: Document /W123/2156602 state is...
Server error
Document /W123/2156602 state is invalid: Cannot create included document because it's not allowed. AllowCreateNewDocument: FALSE{A new document already exists} EntityDescriptor: DocumentEntityDescriptor{tableName=AD_User, fields.count=66}
```

**Comment by teosarca** [comment]
NOTE: to IT: check other places where you can create an included row

**Comment by metas-lc** [comment]
quick IT:
1) new bpartner - add new Contact => works
add new location => works
2) new product - add cu-tu => works
add uom => works
3) new warehouse - add locator 
=> Cannot create included document because it's not allowed.
 AllowCreateNewDocument: FALSE{ParentDocumentNew}↵
 EntityDescriptor: DocumentEntityDescriptor{tableName=M_Locator, fields.count=16}"
path:"/rest/api/window/139/1000002/1/NEW"
NOK

**Comment by metas-lc** [comment]
for no. 3 there is a new issue https://github.com/metasfresh/metasfresh-webui-api/issues/259
problem was it was not saved

**Comment by metas-mk** [comment]
@metas-lc thx. Tested #259 works nicely. Moving this one forward too.
