### ISSUE TITLE
Refactor /process/start response

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#294]
### What is the current behavior?
The process execution result contains fields like:
* reportFilename
* reportContentType
* openViewWindowId
* openViewId
* openDocumentWindowId
* openDocumentId

which basically corresponds to following post process actions:
* open report
* open view
* open single document window

### What is the expected or desired behavior?
Have only one field, called "action", and based on which action it is, we shall have the required fields for that action. i.e.

1. opening a report:
```
{
  type:"openReport",
  filename:"...",
  contentType: "..."
}
```
legacy fields are: reportFilename, reportContentType

2. opening a view
```
{
  type:"openView",
  windowId: ... ,
  viewid: "..."
}
```
legacy fields are: openViewWindowId, openViewId

3. open a single document:
```
{
  type:"openDocument",
  windowId:... ,
  documentId:
}
```
legacy fields are: openDocumentWindowId, openDocumentId

----
NOTE to IT: this is a pure technical task. So the only tests u could perform is regression on starting processes.

**Comment by damianprzygodzki** [comment]
`error` and `summary` stay as they were?

**Comment by teosarca** [comment]
yes, they stay.

**Comment by metas-lc** [comment]
IT
(task is OK, for the NOKs i found will create new tasks)

* jasper process NOK
1. select home button, write revenue, select Revenue Busines Partner
=> nothing happens NOK (jasper process)
2. select browse the whole tree => process opens => nok too late (will create a frontend task)
3. open the process from sitemap => opens fine OK
4. in each case, add date to and date from , start 
=> /rest/api/process/application/pdf/1348430/print/Umsatzreport+Geschäftspartner.pdf  NOK (will create a backend task)
=> error: There was an unexpected error (type=Not Found, status=404).NOK

5. go to business partner window, select an existing one and open the pricelist process from gear
=> data shall be filled but it's not NOK
6. fill in the data , run the report
=> error: There was an unexpected error (type=Not Found, status=404). NOK

* jasper documents OK
1. go to sales or purchase order and select a completed order
2. on actions select print
=> jasper docu opens fine

* jasper labels OK
1. go to material receipt candidates and select a line , open hu editor and run the label process
=> you can't see it because it's not configured but there are no errors

* document creation processes OK
1. go to sales order and create a new one
2. add a product and complete it
3. go to shipment candidate and from gear select the shipment creation process
4. run the process
=> shipment was created OK
5. go back to sales order and open the invoice candidates
6. go to gear and select the process for invoice creation
=> invoices created OK
7. go to purchase order and create a new one, add a product and complete it
8. go to receipt candidates and select the one with the product
9. use the green button to receive your HUs
10. select create material receipt
=> new receipt was created OK
11. go back to your purchase order and open the invoice candidates
12. go to gear and select the process for invoice creation
=> invoices created OK
