### ISSUE TITLE
Address missing in 'Adresse' for bpartner created on-the-fly

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#306]
### Is this a bug or feature request?
Bug
### What is the current behavior?
If you create a bpartner on-the-fly, e.g. in purchase order, and set an address there, then this address is not displayed in Adresse, bpartner window, tab address, only in Anschrift
#### Which are the steps to reproduce?
* open New Purchase Order
* in bpartner field, write e.g jhug, then click on new bpartner
* create a new bpartner on-the-fly, and also set an address there!
* after creating the prder, check the bpartner window for this new bpartner
=> tab address: the address you set when creating the bpartner is displayed in field Anschrift, but not in Adresse
### What is the expected or desired behavior?
The address should be displayed in the Adresse field too.

**Comment by teosarca** [comment]
@metas-dh quick checked on my laptop. It looks ok imho?!

![image](https://cloud.githubusercontent.com/assets/1244701/25278250/cf37ecb6-26aa-11e7-9299-58b6d1a61a4b.png)

**Comment by teosarca** [comment]
UPDATE: found the reason why the C_Location_ID is displayed empty:
* the C_Location_ID display string is built from City
* the City was not filled.

Suggestion:
* make the city mandatory (don't see a reason to not be mandatory)
* introduce C_Location.Address field which shall always contain the prebuilt location string

**Comment by teosarca** [comment]
UPDATE:
* marked C_Location.C_Country_ID as identifier (so it will be part of the lookup display string)

**Comment by metas-lc** [comment]
IT
1. go to purchase order and create a new one
2. start writing a bpartner name that does not exists
3. create a new bpartner on-the-fly, and also set an address there (e.g. aaa 1234 country: DE)
4. finish the order and go to business partner window, see address tab
=> first field is filled with country name (DE) OK
5. right click to Advanced Edit, select the address button, close it
=> notice that now on the address field is "aaa 1234" instead of the country's name OK?

**Comment by metas-mk** [comment]
@metas-lc thanks for testing
about "right click to Advanced Edit, select the address button, close it"
I would leave it like that atm. We can take care of this minor case later.
