### ISSUE TITLE
Manufacturing Issue/Receipt: Fix Qty and QtyPlan columns

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#322]
### What is the current behavior?
Qty and QtyPlan are wrong and confusing.

#### Which are the steps to reproduce?
* open Manufacturing Issue/Receipt
* make sure you have something issued and receipt (so see some numbers)

### What is the expected or desired behavior?
QtyPlan
	* Main product/BOM line: the quantities calculated when MO is created/completed (and ALWAYS stays!!!)
	* HU: always empty (not even ZERO)
Qty 
	* Main product/BOM line: SUM of HUs beneath
	* HU: the HU's QtyCU

Required for https://github.com/metasfresh/metasfresh-webui-api/issues/269

**Comment by metas-lc** [comment]
IT
1. open Manufacturing Issue/Receipt
2. make sure you have something issued and receipt
=> qty plan: on main product or bom: same as the qty planed from manufacturing (on HU lines is always empty)
=> qty: main product/ bom: sum of the hu's qty beneath
=> qty: hu: the HU's qty CU

only issue i found is that when you select both TU and VHU when you issue they gt separated as 2 different HUs and the qty gets doubled. Created a task since is not related:
https://github.com/metasfresh/metasfresh-webui-api/issues/333
