### ISSUE TITLE
Implement webui HUEditor support for massive amount of HUs

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#330]
### What is the current behavior?
HUEditor was designed for a small amount of HUs.
Usually that's the case when you are receiving HUs.

### What is the expected or desired behavior?
HUEditor shall handle the case when we are browsing a huge amount of HUs.
e.g.
* Manufacturing Issue/Receipt, select HUs to issue

**Note to IT: requires full regression on webui with main focus on HUs.**

**Comment by teosarca** [comment]
UPDATE: flagging the task as integrated because actually we delivered some partial work on it (i.e. refactoring atm)

**Comment by teosarca** [comment]
reopening because i've closed it by mistake

**Comment by metas-dh** [comment]
Results of IT1
tested on sp80 WebUI (since there is more masterdata for production than in w101)

HUEditor shall handle the case when we are browsing a huge amount of HUs: Issue in Manufacturing:
* huge amount of HUs in HU Editor, in manufacturing warehouse: tested with 50, 100, 150 HUs etc: HU Editor for issueing gets more and more pages: OK
* you can navigate from page to page using arrows, or jump to a certain page by clicking on it or click on ... and enter the page you want to jum to: OK
* Selecting and issueing a HU works fine: OK
* Selecting and issueing >1 HU  (from the same page) works fine: OK
* Using Barcode for selecting a HU works fine (HU on the page which is displayed): OK
* HU status after issueing / receiving in manufacturing: the same as the Status of the PP_Order (Planning when PP_Order: Status Planning, Active when  PP_Order: Status Complete)
* Transforming in HU Editor for Issue HUs works fine: OK
* Qties of products updated correctly after issueing (also for >1 HU, and transformed HU): OK

Questions and problems:
* Using Barcode only works for the HU included on the selected page, so if i'm on page 2 for Issueing, in HU Editor, and want to select a certain HU on another page, then the Barcode does not work, the HU does not get selected
* Selecting >1 HU from different pages  for Issueing, in HU Editor does not work, you can only select HUs from the same page
* HU Editor for Issueing HUs opens correctly when selected Issue/Receipt for the PP_Order in grid view, displaying the HUs to select from for Issue,  but when selecting Issue/Receipt for the PP_Order in single view, Actions, the HU Editor with the HUs to select from was not displayed

Regression testing for HUs, questions and problems:
* Wareneingang for TU type Paloxe: Actions button always shows only 1 Paloxe for inout, not more; when i have ordered a high number of Paloxen and want to receive those, i have to use 
Actions: receive CU - Transform - put CUs on new TUs - select TU type - and set CU qty, which is quite time consuming
* Actions: receive HUs does not work for Paloxen: LU field is mandatory, and i can select EUR-Tauschpalette there or Virtual PI, but Paloxe cannot be put on those; No Handling Unit is not available for LU (as in Swing)
* Handling Unit window: search for Barcode using HU value did not work, nothing found (although HU was displayed in HU Editor for Issueing)
* no other filter / search options in Handling Unit window: HU status, warehouse, bpartner etc.??

**Comment by metas-lc** [comment]
IT
checked all questions and problems- they are either wanted or solved (documented above) OK
