### ISSUE TITLE
Vendor Return Actions in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#396]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the new Vendor Return Actions from Swing Client are missing in WebU
#### Which are the steps to reproduce?
Open the standalone HU Editor or the modal one in Material Receipt and see.
### What is the expected or desired behavior?
The Vendor Return Actions (Disposal, WH Movement, Vendor Return) shall be added to the Material Receipt HU Editor and Standalone HU Editor in WebUI.

![image](https://cloud.githubusercontent.com/assets/1244701/26305266/41a9902e-3ef7-11e7-80a8-ade2b25eea48.png)

**Comment by metas-rc** [comment]
* Should also solve the problem in https://github.com/metasfresh/metasfresh/issues/1605. Please, move this task to done when fixed, too.

**Comment by teosarca** [comment]
Update: 
* implemented the Move to quality warehouse quick action
* regression test on swing is needed

**Comment by teosarca** [comment]
Update: also implemented the "Move to quality issues warehouse" and "Dispose" actions.

NOTE: they are on first preview version so i think we still have to refine here and there...

**Comment by metas-lc** [comment]
IT
I. Webui
1. material receipt candidates:
- hu editor: dispose, move to quality warehouse, return from customer (should not be visible), return to vendor
- korrektur: dispose, move to quality warehouse, return from customer (should not be visible), return to vendor

2. manufacturing order: when you select the co-product and press issue, you have: dispose, move to quality warehouse, return from customer (should not be visible), return to vendor

3. creating dispose/returns/movements (from receipt cands and manufacturing-issue, for HUs that have assignments)
- Dispose:
Process error
* Not found * Document Type - Document BaseType : Physischer Warenbestand (SO Sub Type: MD, Client: 1000000, Organization: 1000000)
- return from customer (works from receipt cands but shouldn't) NOK
- return to vendor - works OK
- movement to quality - works OK


II. Swing:
1. receipt pos: 
- only in korrectur: dispose, move to quality warehouse, return to vendor OK

2. HU POS: dispose, move to quality warehouse, return to vendor OK

3. shipment with picking: "Return from customer" readonly on draft and editable on complete OK

4. creating dispose/returns/movements
- customer return - works OK
- move to quality warehouse - works OK (https://github.com/metasfresh/metasfresh/issues/1605 also works. the location is the same - HU's one - when testing it from both receipt pos and hu pos)
- vendor return - works OK
- dispose NOK
* Nicht gefunden * Belegart - Document BaseType : Physischer Warenbestand (Doc Sub Type: MD, Mandant: 1000000, Sektion: 1000000)
 
note: about "creating dispose/returns/movements" didn't test in deep. I'll do a proper test on individual tasks. Tested only simple cases.

NOKs: 

1. webui
- Material Receipt Candidates: return from customer is visible + works (creates return). Also those buttons shall be visible only if there are assignments. In my case they were visible on hu editor too. 
=> will be fixed in https://github.com/metasfresh/metasfresh/issues/1699

-  Document BaseType : Physischer Warenbestand (SO Sub Type: MD) is missing
=> will be solved in https://github.com/metasfresh/metasfresh/issues/1064

- in korrektur destroyed HUs are still visible and you can create returns for them => will be solved in https://github.com/metasfresh/metasfresh/issues/1327


2. swing
- hu editor for customer returns looks weird, but it works
=> will be solved in https://github.com/metasfresh/metasfresh/issues/1700

- Document BaseType : Physischer Warenbestand (SO Sub Type: MD) is missing 
=> will be solved in https://github.com/metasfresh/metasfresh/issues/1064
