### ISSUE TITLE
Support Zooming to NULL values

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#401]
### Is this a bug or feature request?
feature request

### What is the current behavior?
if you want to use zoom on a field which is NULL you get:

![image](https://cloud.githubusercontent.com/assets/16079655/26278803/b25179cc-3da3-11e7-9304-ce26ccdb91d7.png)

```
Error: Cannot fetch ZoomInto infos...
Cannot fetch ZoomInto infos from a null value

```
#### Which are the steps to reproduce?
1. go to sales order window
1. create new record
1. click on partner field while its still empty

### What is the expected or desired behavior?
open the window linked to the field - just empty like it works in java swing client

### Severity
1. When setting master data its extremely helpful if you can jump into the needed windows with just a click. 
1. If you do not the value you need to trigger the auto complete you could just click on the fields name to look up the values. Would be another problem solved.

**Comment by teosarca** [comment]
We will do it completely different.
See the frontend task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/793

**Comment by teosarca** [comment]
Implemented. When the vaue is null it will open a new browser tab with a new document of that kind.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Testing. Waiting for next rollout.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* When zooming into a null value (e.g. in the partner of a new document) a new tab is opened in the browser for creating a new entry in the table C_BPartner
* You have to go back to the initial document and set a partner but you still have to type some letters of the name. But I suppose this is ok, because of this comment: 
> Implemented. When the vaue is null it will open a new browser tab with a new document of that kind.

* Regression: zooming into an existing entry still works correctly, a new tab opens poiting to that entry.
