### ISSUE TITLE
backend: change view attributes endpoint location

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#409]
### What is the current behavior?
Current view attributes endpoint is /rest/api/documentView/{windowId}/{viewId}/{rowId}

### What is the expected or desired behavior?
Change it to: /rest/api/documentView/{windowId}/{viewId}/{rowId}/attributes
i.e. we will append the "/attributes" because we want to avoid overlapping with other endpoints will be based on current view row (/rest/api/documentView/{windowId}/{viewId}/{rowId}).

#### Which are the steps to reproduce?
Browse some HUs in https://w101.metasfresh.com:8443/window/540189
Mind the attributes related endpoint calls.

**Comment by teosarca** [comment]
Frontend task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/783

**Comment by teosarca** [comment]
Note to IT: quick regression on all things which have fields and typeahead/dropdowns is needed
* window
* grid view
* address editor
* ASI editor
* process parameters
* HU Editor -> Attributes

**Comment by metas-lc** [comment]
IT
1) checked asi and other dropdowns in different places as described above
=> mostly works fine

2) stuff i found: 
- window 256 included tab, try to change an attribute => error. will be solved in: https://github.com/metasfresh/metasfresh-webui-api/issues/454
- n instead of none in dropdowns: will be solved in: https://github.com/metasfresh/metasfresh-webui-frontend/issues/877
