### ISSUE TITLE
Password process parameters shall allow showing the password

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#453]
See https://github.com/metasfresh/metasfresh-webui-frontend/issues/863

We will hardcode/implement it so in case we have a process parameter which is a password, we will set the allowShowPassword to true.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* went to https://w101.metasfresh.com:8443/window/53100, selected a partner ans chose " Change my password" 
* There are 3 password fields there: old password, new password and confirm new password
* OK:  When I write in any of them, the characters are not displayed, but there is "*****"  instead of them 
* OK: There is an eye icon near each of the password fields.
* OK: If I click the eye icons I can briefly see what I wrote in the password fields
* OK: I can see the content of the passwords for as long as I keep the eye icon clicked, then they are back to "*********"
