### ISSUE TITLE
No Role Error for new User

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#482]
### Is this a bug or feature request?
Bug (low prio)
### What is the current behavior?
Sometimes a freshly created user, is not directly useable after creation. When login then the error "No Roles" is returned.
#### Which are the steps to reproduce?
a) Login as Admin. Open The window User. Create a new User as System User w/ Login and Password. Logout. Try to Login as new User. Must fail because no Role is assigned. Wait for the error message. Now login again as Admin. Go to window Role. Assign the newly created user to a Role. Logout. Try to Login as newly created User. The error from before about the "No Role" still persists. Do a Swagger Cache reset, and you can login again.
### What is the expected or desired behavior?
Shall be able to login w/o cahce reset.

**Comment by teosarca** [comment]
note: implemented. Additionally, the AD_User_Roles records will be deleted when the AD_Role is deleted.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
tested cases above
a) Login as Admin. Open The window User. Create a new User as System User w/ Login and Password. Logout. Try to Login as new User. Must fail because no Role is assigned. Wait for the error message. => "No Role"
Now login again as Admin. Go to window Role. Assign the newly created user to a Role. Logout. Try to Login as newly created User. => you are now logged in with the new user
go to user window and remove the role, logout, login =>  "No Role"
login with admin, go to user window and add the role from there. Logout, login with the new one => works OK
