### ISSUE TITLE
Provide mass export of Data to Excel

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#547]
### Is this a bug or feature request?
feature request

### What is the current behavior?
you can only copy the data you see on one page of a window 

### Which are the steps to reproduce?

NA

### What is the expected or desired behavior?
Have a way to export all data which is selected to a File that can be downloaded and opened in excel

**Comment by metasnw** [comment]
want to use that feature to export huge amounts of data (e.g. contacts and addresses) from a generic window

**Comment by metas-mk** [comment]
I would propose to start the export in a given window. Then the job is triggered async. the data/ file is selected and stored. The user receives a notification that includes the download link.

**Comment by teosarca** [comment]
update: the export is done in a separate thread (managed by a special thread pool executor service).
I didn't implemented it using the async framework because on that level i don't have all the infos.

At the moment the executor service config is hardcoded, but easily, we will able able make it configurable. See https://github.com/metasfresh/metasfresh-webui-api/blob/98f3a4c56bfc10c97b3e2d37a84e1872eef8c666/src/main/java/de/metas/ui/web/view/ViewRestController.java#L118

**Comment by teosarca** [comment]
note to IT: would be easier to test when the frontend task is done.
Also pls make sure you are testing following cases:
* no selection
* select some rows
* select ALL rows (from all pages)

**Comment by metas-lc** [comment]
IT
tested in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1197 OK
