### ISSUE TITLE
Picking Window: Open HU Selection window filtering

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#557]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the HU Selection window is opened with all Handling Units available.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
The Handling Units shall initially be opened only w/ Handling Units fitting to the selected Picking Line and Product.

![image](https://user-images.githubusercontent.com/13365687/29866453-b931754c-8d78-11e7-914a-c1453d84ee11.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. Create a new sales order, for product A, in warehouse X
2. Create a purchase order I, for product A, warehouse X (same packing item as used in sales order)
3. Create another purchase order II, for product B, warehouse X
4. Create a 3rd purchase order III, for product A, warehouse Y
5. Open Material Receipt Candidates for all purchase orders, and receive the products (note the HU values!), BUT not the whole qty!
6. Open Picking Terminal, select your sales orderline, press Pick
7. In Picking Terminal, select a Picking Slot and press Open HU selection window:
 * HUs received for purchase order I are displayed and selectable, since it's the same product as ordered and the correct warehouse: OK
 * HUs received for purchase order II are not displayed, since another product was ordered and received: OK
 * HUs received for purchase order III are not displayed, since the product was received in another warehouse: OK
8. Select the HUs of product A, pick them and process the picking
9. Go back to Material Receipt Candidates, and create receipts for purchase order I (note the HU values!):
 * receive  some qty, but with a different packing item
 * receive some qty, then do Korrektur, so the HUs will be destroyed
10. Check Handling Unit Editor:
 * remaining qty from purchase orders which are not yet received have HU status Planning
 * HUs from Korrektur have status Destroyed
11. Open Picking Terminal again for your sales order, and check the Open HU selection window:
 * HUs which were picked before are not displayed anymore: OK
 * HUs which were destroyed with Korrektur are not displayed: OK
 * HUs with status Planning from purchase order I are not displayed: OK
 * HUs received for purchase order I with the different packing item are displayed and selectable: OK for now, might be changed in the future
