### ISSUE TITLE
Source HU Actions shall only be "Drop Source HU"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#683]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are Source HU Actions available that are not useful for the user.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Reduce the actions of selected Source HU to only "Drop Source HU".

![image](https://user-images.githubusercontent.com/13365687/32931613-4d9c50ce-cb65-11e7-9e02-2c4e65323de2.png)

**Comment by teosarca** [comment]
NOTE: in case of Pick process, I've decided to hide this action when is not available, because we want to cover the requirements of https://github.com/metasfresh/metasfresh-webui-api/issues/683, were we need to hide the action for source HU lines... and does not worth the effort to handle particularly that case.
Before this change, the action was shown but it was disabled.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

still have more Actions available for Source HU then "Drop Source HU":

production:
![2017-11-22 11_31_05-metasfresh](https://user-images.githubusercontent.com/18696715/33123408-6c3c81c0-cf7a-11e7-8288-657d5f0bdca9.png)


picking:
![2017-11-22 11_33_01-](https://user-images.githubusercontent.com/18696715/33123430-7b0c1d0a-cf7a-11e7-9df6-b17f80b89e66.png)

**Comment by teosarca** [comment]
update: the picking is OK as it is. have to check the source HUs part...

**Comment by teosarca** [comment]
update: about manufacturing issue/receipt. I've took a look at those 3 processes:

* Verarbeiten (de.metas.ui.web.pporder.process.WEBUI_PP_Order_ChangePlanningStatus_Complete)
* Zur Prüfung freigeben (de.metas.ui.web.pporder.process.WEBUI_PP_Order_ChangePlanningStatus_Review)
* Soll keine Quell-HU mehr sein (de.metas.ui.web.pporder.process.WEBUI_PP_Order_M_Source_HU_Delete)

The `Verarbeiten` and `Zur Prüfung freigeben` are shown whatever you select because those actions are about the manufacturing order and not about what u selected.

So, IMHO it's OK.

wdyt?

**Comment by metas-dh** [comment]
> The Verarbeiten and Zur Prüfung freigeben are shown whatever you select because those actions are about the manufacturing order and not about what u selected.
So, IMHO it's OK.

agree; @metas-mk wdyt?

**Comment by metas-dh** [comment]
checked w/ metas-mk: OK
