### ISSUE TITLE
picking terminal: show BPartner instead of DeliveryDate

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#687]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, BPartner & Location is missing in Picking Window
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the BPartner to Picking modal overlay instead of Shipment Date. In Picking Slot view, add the BPartner and Location next to Picking Slot No. as soon Picking Slot is reserved.

![image](https://user-images.githubusercontent.com/13365687/32978377-7086bc32-cc41-11e7-8139-c8267fa639ba.png)

**Comment by teosarca** [comment]
update: about picking slot's Partner/Location, actually they are displayed but the picking slot is never dynamically allocated in webui, so far.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* BPartner to Picking modal overlay instead of Shipment Date: OK
* Picking Slot view: add the BPartner and Location next to Picking Slot No. as soon Picking Slot is reserved: solved in #695 

![2017-11-28 09_23_22-metasfresh](https://user-images.githubusercontent.com/18696715/33309349-29a0b4be-d41e-11e7-864a-8bbfe49bc522.png)
