### ISSUE TITLE
Import File Loader substitute in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#879]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to import data via WebUI.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Intermediate solution: Create a new Window that takes the Import Format and allows to drag&drop the import file onto it. Then the user starts an action to import into the i_<tables>. After the import is done, the "attachment" is deleted.
Needed for I_BPartner, I_Product, I_ProductPharma for now.
Add Document Reference for the Imported data to the target table/ window so the user can directly jump there after import.

**Comment by teosarca** [comment]
note to IT:
* the Data Import window is 540419.... or wait for https://github.com/metasfresh/metasfresh-webui-api/issues/882 to have it in menu
* pls do regression for swing import

![image](https://user-images.githubusercontent.com/1244701/36696249-56379c66-1b4c-11e8-9ffc-750878c5bb21.png)

![image](https://user-images.githubusercontent.com/1244701/36696264-65815586-1b4c-11e8-96e1-093cf791f726.png)

**Comment by metas-lc** [comment]
IT
note: tested before the window was added in menu
1. open window Data Import (540419)
2. create a new one, choose a format (e.g. standard product)
3. drag and drop a csv file
note: i had to add 2 files because the dropdown was not working with just 1 entry. Shall be solved by https://github.com/metasfresh/metasfresh-webui-frontend/issues/1622
4. go to actions, select Import
5. on dropdown select your file
=> you get a notification that 3 records were imported
6. go to Product window 
=> the products were imported

Regression: same steps on swing => products are imported OK
